[supabase]
url = "https://flktguggioxnqaccztzi.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZweHZ2a2l6eXFnbXJ6aGZ3cHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTEwOTYsImV4cCI6MjA2ODg2NzA5Nn0.xnvCreITaTlMr1CJI3QIHT-dhpfJlKZtfMMu5UtLrek"
