[supabase]
url = "https://flktguggioxnqaccztzi.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsa3RndWdnaW94bnFhY2N6dHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjMzMzAsImV4cCI6MjA2ODg5OTMzMH0.xx4QahULgD7E9FayisbTb9xg6U5RTA1L7GYGn8bTF4E"
